# Spring boot app config

server:
  port: 9501

logging:
  level: { root: ERROR, portal: DEBUG }

portal:
  swagger: { enable: true }
  scheduling: { enable: false, taskPing: '*/10 * * * * *' }

spring:
  thymeleaf: { cache: false }

management:
  server: { port: 9091 }
  endpoints:
    web:
      base-path: /monitoring
      exposure: { include: '*' }
