spring:
  profiles: debug
  profiles.include:
    - server
    - snow-debug

snow:
  anotherMessage: "another message debug"

---

spring:
  profiles.include:
    - server
    - snow-production

snow:
  anotherMessage: "another message prod"
