snow:
  anotherMessage: "another message for all"

---
spring:
  profiles: debug
  profiles.include:
    - server
    - snow-debug

---

spring:
  profiles.include:
    - server
    - snow-production
