// Code generated by qtc from "base.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line pkg/util/base.qtpl:1
package util

//line pkg/util/base.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line pkg/util/base.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line pkg/util/base.qtpl:2
type Page interface {
//line pkg/util/base.qtpl:2
	Title() string
//line pkg/util/base.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line pkg/util/base.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line pkg/util/base.qtpl:2
	Body() string
//line pkg/util/base.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line pkg/util/base.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line pkg/util/base.qtpl:2
}

//line pkg/util/base.qtpl:8
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line pkg/util/base.qtpl:8
	qw422016.N().S(`
<html>
	<head>
		<title>`)
//line pkg/util/base.qtpl:11
	p.StreamTitle(qw422016)
//line pkg/util/base.qtpl:11
	qw422016.N().S(`</title>
	</head>
	<body>
		`)
//line pkg/util/base.qtpl:14
	p.StreamBody(qw422016)
//line pkg/util/base.qtpl:14
	qw422016.N().S(`
	</body>
</html>
`)
//line pkg/util/base.qtpl:17
}

//line pkg/util/base.qtpl:17
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line pkg/util/base.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/util/base.qtpl:17
	StreamPageTemplate(qw422016, p)
//line pkg/util/base.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line pkg/util/base.qtpl:17
}

//line pkg/util/base.qtpl:17
func PageTemplate(p Page) string {
//line pkg/util/base.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/util/base.qtpl:17
	WritePageTemplate(qb422016, p)
//line pkg/util/base.qtpl:17
	qs422016 := string(qb422016.B)
//line pkg/util/base.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/util/base.qtpl:17
	return qs422016
//line pkg/util/base.qtpl:17
}

//line pkg/util/base.qtpl:19
type BasePage struct {
	HeadTitle string
	MainBody  string
}

//line pkg/util/base.qtpl:24
func (p *BasePage) StreamTitle(qw422016 *qt422016.Writer) {
//line pkg/util/base.qtpl:24
	qw422016.E().S(p.HeadTitle)
//line pkg/util/base.qtpl:24
}

//line pkg/util/base.qtpl:24
func (p *BasePage) WriteTitle(qq422016 qtio422016.Writer) {
//line pkg/util/base.qtpl:24
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/util/base.qtpl:24
	p.StreamTitle(qw422016)
//line pkg/util/base.qtpl:24
	qt422016.ReleaseWriter(qw422016)
//line pkg/util/base.qtpl:24
}

//line pkg/util/base.qtpl:24
func (p *BasePage) Title() string {
//line pkg/util/base.qtpl:24
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/util/base.qtpl:24
	p.WriteTitle(qb422016)
//line pkg/util/base.qtpl:24
	qs422016 := string(qb422016.B)
//line pkg/util/base.qtpl:24
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/util/base.qtpl:24
	return qs422016
//line pkg/util/base.qtpl:24
}

//line pkg/util/base.qtpl:26
func (p *BasePage) StreamBody(qw422016 *qt422016.Writer) {
//line pkg/util/base.qtpl:26
	qw422016.N().S(`
<div>
    <a href="/users">goto users page</a>
</div>
<h1>`)
//line pkg/util/base.qtpl:30
	qw422016.E().S(p.HeadTitle)
//line pkg/util/base.qtpl:30
	qw422016.N().S(`</h1>
<p>`)
//line pkg/util/base.qtpl:31
	qw422016.E().S(p.MainBody)
//line pkg/util/base.qtpl:31
	qw422016.N().S(`</p>
`)
//line pkg/util/base.qtpl:32
}

//line pkg/util/base.qtpl:32
func (p *BasePage) WriteBody(qq422016 qtio422016.Writer) {
//line pkg/util/base.qtpl:32
	qw422016 := qt422016.AcquireWriter(qq422016)
//line pkg/util/base.qtpl:32
	p.StreamBody(qw422016)
//line pkg/util/base.qtpl:32
	qt422016.ReleaseWriter(qw422016)
//line pkg/util/base.qtpl:32
}

//line pkg/util/base.qtpl:32
func (p *BasePage) Body() string {
//line pkg/util/base.qtpl:32
	qb422016 := qt422016.AcquireByteBuffer()
//line pkg/util/base.qtpl:32
	p.WriteBody(qb422016)
//line pkg/util/base.qtpl:32
	qs422016 := string(qb422016.B)
//line pkg/util/base.qtpl:32
	qt422016.ReleaseByteBuffer(qb422016)
//line pkg/util/base.qtpl:32
	return qs422016
//line pkg/util/base.qtpl:32
}
