openapi: "3.0.1"
info: { version: 1.0.0, title: Stray }
servers: [{url: /api}]

paths:
  /version:
    tags: [General]
    get:
      responses:
        '200':
          description: Version Info
          content: {application/json: {schema: {$ref: './common.yaml#/components/schemas/VersionInfo'}}}
  /v1/debug/echo:
    post:
      tags: [Debug]
      requestBody:
        content: {application/json: {schema: {$ref: './debug.yaml#/components/schemas/DebugEchoOptions'}}}
      responses:
        '200':
          description: OK
          content: {application/json: {schema: {$ref: './debug.yaml#/components/schemas/DebugEchoResponse'}}}
