// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package server

// DebugEchoOptions defines model for DebugEchoOptions.
type DebugEchoOptions struct {
	Msg string `json:"msg"`
}

// DebugEchoResponse defines model for DebugEchoResponse.
type DebugEchoResponse struct {
	Msg string `json:"msg"`
}
